# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Feed-Loader build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses : actions/checkout@v4 # ставит working-directory в корень проекта

    - name: Set up Go 1.23.3
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.3'

    - name: Run linter
      uses: golangci/golangci-lint-action@v6
      with:
        args: --timeout=30s --config=.golangci.yaml

    - name: Launch tests
      working-directory: ./services/feed-loader
      run: go test -v ./...

